# enhanced_technique_g.py


def run():
    print("\n🔌 Electrophysiological Methods")
    print("=" * 70)
    print("🔍 Techniques to measure electrical activity in biological systems.\n")

    techniques = {
        1: ("Single neuron recording", "⭐⭐⭐☆☆ Intermediate | ⏱️ 2-4 hours | 💰 $$"),
        2: ("Patch-clamp recording", "⭐⭐⭐⭐☆ Advanced | ⏱️ 4-6 hours | 💰 $$$"),
        3: ("Electrocardiography (ECG)", "⭐⭐☆☆☆ Beginner | ⏱️ 1-2 hours | 💰 $"),
        4: ("Brain activity recording (EEG/MEG)", "⭐⭐⭐☆☆ Intermediate | ⏱️ 2-4 hours | 💰 $$"),
        5: ("Lesion and stimulation of brain regions", "⭐⭐⭐⭐⭐ Expert | ⏱️ 1-2 days | 💰 $$$$"),
        6: ("Pharmacological testing using electrophysiology", "⭐⭐⭐⭐☆ Advanced | ⏱️ 1 day | 💰 $$$"),
        7: ("Functional brain imaging (PET, MRI, fMRI, CAT)", "⭐⭐⭐⭐☆ Advanced | ⏱️ 1-3 days | 💰 $$$")
    }

    while True:
        print("\n📘 Choose a technique to explore:")
        for key, (title, meta) in techniques.items():
            print(f" {key:2d}. {title}\n     {meta}")

        try:
            choice = int(input("\nEnter the number of the technique: "))
            if choice not in techniques:
                print("❌ Invalid choice.")
                continue

            title, _ = techniques[choice]
            print(f"\n🧪 Step-by-Step Workflow: {title}")
            print("=" * 80)
            print(f"\n📖 Intro: {get_intro(choice)}\n")


            steps = get_workflow(choice)
            total = len(steps)
            for i, step in enumerate(steps, 1):
                print(f"\n📌 Step {i}/{total}: {step}")
                progress = "█" * (i * 25 // total) + "░" * (25 - i * 25 // total)
                print(f"Progress: [{progress}] {i * 100 // total}%")
                if i < total:
                    cont = input("   Press Enter to continue (or 'q' to stop): ")
                    if cont.lower() == 'q':
                        break

            again = input("\n🔁 Do you want to try another technique from this section? (y/n): ").strip().lower()
            if again == 'y':
                continue

            switch = input("\n📚 Do you want to switch to another section (A–H)? (y/n): ").strip().lower()
            if switch == 'y':
                from main import run_main_menu
                run_main_menu()
                return
            else:
                print("\n👋 Exiting the tool. Thank you!")
                return

        except ValueError:
            print("❌ Please enter a valid number.")

def get_intro(option):
    intros = {
        1: (
            "Intracellular and extracellular microelectrode recording is a fundamental technique for studying the electrical activity of neurons. "
            "It involves inserting fine electrodes into or near individual cells to detect voltage changes. "
            "These recordings provide valuable information about action potentials, synaptic inputs, and firing patterns. "
            "The data help researchers understand how neurons encode and transmit information. "
            "This method is widely used in both basic neuroscience and applied neurophysiology."
        ),
        2: (
            "Patch-clamp recording is a gold-standard method for investigating ion channels and membrane potentials in cells. "
            "A glass micropipette forms a tight seal with the cell membrane, allowing precise electrical measurements. "
            "This approach can be performed in different configurations, such as whole-cell or single-channel recording. "
            "It enables researchers to study the effects of drugs, neurotransmitters, and other modulators on channel function. "
            "Patch-clamp is indispensable for electrophysiology, pharmacology, and biophysics research."
        ),
        3: (
            "Electrocardiography (ECG or EKG) is a non-invasive method to assess the electrical activity of the heart. "
            "Electrodes placed on the skin detect voltage changes generated by cardiac muscle contractions. "
            "The resulting waveform provides information about heart rate, rhythm, and conduction pathways. "
            "ECG is essential for diagnosing arrhythmias, ischemia, and other cardiac conditions. "
            "It is a routine tool in both clinical and research settings."
        ),
        4: (
            "Electroencephalography (EEG) measures the brain's electrical activity using electrodes placed on the scalp. "
            "It captures rhythmic patterns and transient events that reflect neural processing. "
            "EEG is widely used to study sleep, epilepsy, sensory processing, and cognitive functions. "
            "Its high temporal resolution makes it ideal for tracking fast brain dynamics. "
            "When combined with event-related potentials (ERPs), EEG can reveal time-locked brain responses to stimuli."
        ),
        5: (
            "Lesion and stimulation studies are key methods for exploring brain function. "
            "Lesions, created surgically or chemically, allow researchers to determine the role of specific brain regions. "
            "Electrical or optogenetic stimulation activates targeted neural circuits to study their effects on behavior and physiology. "
            "These approaches provide causal evidence linking brain areas to specific functions. "
            "They are frequently used in behavioral neuroscience and neuropharmacology."
        ),
        6: (
            "Pharmacological manipulation involves applying drugs to neural tissue or entire organisms to study their effects on the nervous system. "
            "Agonists, antagonists, and other compounds can modulate receptor activity, neurotransmission, and signaling pathways. "
            "The resulting changes can be monitored through electrophysiology, imaging, or behavioral assays. "
            "This method is crucial for understanding drug mechanisms and for developing new treatments. "
            "It also plays an important role in neurotoxicology and safety testing."
        ),
        7: (
            "Positron Emission Tomography (PET) is an imaging technique that uses radiolabeled tracers to study metabolic and molecular processes in vivo. "
            "A common tracer, 18F-FDG, highlights regions with high glucose uptake, often indicating increased activity or disease. "
            "PET produces 3D images by detecting gamma rays from positron annihilation events. "
            "It is valuable in oncology, neurology, and pharmacokinetics research. "
            "When combined with MRI or CT, PET provides both functional and structural information."
        ),
        8: (
            "Magnetic Resonance Imaging (MRI) is a powerful non-invasive imaging method that uses magnetic fields and radio waves to visualize soft tissues. "
            "Functional MRI (fMRI) detects blood oxygen level-dependent (BOLD) signals to map brain activity during tasks. "
            "MRI offers high spatial resolution and can be repeated without ionizing radiation exposure. "
            "It is widely used in neuroscience, clinical diagnostics, and cognitive research. "
            "fMRI is especially important for studying brain networks and functional connectivity."
        ),
        9: (
            "Computed Tomography (CT) scanning uses X-rays and computational reconstruction to produce detailed cross-sectional images of the body. "
            "It is faster than MRI and particularly useful in emergency situations for detecting fractures, bleeding, and internal injuries. "
            "CT can also be enhanced with contrast agents to visualize blood vessels and soft tissues more clearly. "
            "This imaging method is widely used in neurology, oncology, and trauma medicine. "
            "Its speed and accuracy make it a mainstay of modern diagnostic imaging."
        )
    }
    return intros.get(option, "No description available.")


def get_workflow(option):
    workflows = {
        1: [
            "Use microelectrodes to record the electrical potential from individual neurons.",
            "Insert electrode into or near neuron in anesthetized or awake animal models.",
            "Amplify and digitize signals using amplifiers and analog-to-digital converters.",
            "Analyze action potentials and firing patterns to study neural coding."
        ],
        2: [
            "Use a glass pipette electrode to form a tight seal with the cell membrane.",
            "Apply gentle suction to rupture membrane for whole-cell patch configuration.",
            "Measure ion channel activity or membrane potentials in real-time.",
            "Apply pharmacological agents to study receptor/channel function."
        ],
        3: [
            "Attach electrodes to chest and limbs of the subject to detect heart signals.",
            "Record electrical activity over time to evaluate heart rhythm and conduction.",
            "Analyze P, QRS, and T waves for diagnosis of arrhythmias, ischemia, etc.",
            "Non-invasive and widely used in cardiology clinics and hospitals."
        ],
        4: [
            "Place electrodes on scalp to measure voltage fluctuations caused by brain activity.",
            "EEG signals are typically in microvolt range and require amplification.",
            "Used to study sleep, epilepsy, cognition, and neural disorders.",
            "Can be combined with event-related potentials (ERPs) in cognitive studies."
        ],
        5: [
            "Lesion: Surgically or chemically destroy specific brain regions to study function.",
            "Stimulation: Apply electrical or optogenetic stimulation to targeted brain areas.",
            "Monitor changes in behavior or physiology post-intervention.",
            "Used in behavioral neuroscience and neuropharmacology research."
        ],
        6: [
            "Apply drugs (e.g., agonists, antagonists) to neural tissue or organism.",
            "Monitor physiological responses (e.g., firing rate, behavior, BOLD signals).",
            "Combine with patch-clamp, EEG, or imaging for mechanism studies.",
            "Important for neurotoxicology and drug development."
        ],
        7: [
            "Inject positron-emitting radiotracer (e.g., 18F-FDG) into the body.",
            "Tracer accumulates in metabolically active tissues.",
            "Positron emission is detected by PET scanner to reconstruct 3D images.",
            "Used for cancer detection, brain metabolism, and drug activity mapping."
        ],
        8: [
            "MRI uses strong magnetic fields and radio waves to visualize soft tissues.",
            "Functional MRI (fMRI) detects BOLD (blood oxygen level-dependent) signals.",
            "Subjects perform tasks while brain regions are imaged dynamically.",
            "Used to study brain connectivity, cognition, and mental health disorders."
        ],
        9: [
            "Uses X-rays and computer processing to generate cross-sectional images.",
            "Non-invasive imaging of bone, brain, and internal organs.",
            "Faster than MRI and often used in emergency diagnostics.",
            "Can be enhanced with contrast agents for vascular imaging."
        ]
    }
    return workflows.get(option, ["Workflow not available yet."])
